version: "3"
services:   
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/
    env_file: 
      - .env
    expose:
      - 5050
    command: uwsgi --ini docker/uwsgi.ini
  
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5050:80
    depends_on:
      - server
